/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.killa.sierravp.gui;

/**
 *
 * @author jaraj
 */
public class SistemaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form SistemaAlumno
     */
    public SistemaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ButtonPerfil = new javax.swing.JButton();
        ButtonMatricula = new javax.swing.JButton();
        ButtonSocial = new javax.swing.JButton();
        ButtonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Perfil = new javax.swing.JPanel();
        InfoPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nombres = new javax.swing.JTextField();
        Dni = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Facultad = new javax.swing.JTextField();
        Escuela = new javax.swing.JTextField();
        Codigoalumno = new javax.swing.JTextField();
        Correoalumno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CRAalumno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Matricula = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Tablaturnoalumno = new javax.swing.JScrollPane();
        TablaTurnoFecha = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Social = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Buscargrupo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Notificacion = new javax.swing.JButton();
        compañeroencontrado = new javax.swing.JPanel();
        abrirpaneldemensaje = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cualidadescompañero = new javax.swing.JTextField();
        nombredecompañero = new javax.swing.JTextField();
        Notificacionpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        vermensajede = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        teenviounmensaje = new javax.swing.JTextPane();
        minimizarnotis = new javax.swing.JButton();
        PanelDeMensaje = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        recibidordemensaje = new javax.swing.JTextField();
        chatdemensajes = new javax.swing.JPanel();
        Enviarmensaje = new javax.swing.JButton();
        escribirmensaje = new javax.swing.JTextField();
        cerrarmensaje = new javax.swing.JButton();
        loquenoquieroSOCIAL = new javax.swing.JComboBox<>();
        loquequieroSOCIAL = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jTextField13.setText("jTextField13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 26, 78));

        ButtonPerfil.setBackground(new java.awt.Color(3, 36, 102));
        ButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfilicon.png"))); // NOI18N
        ButtonPerfil.setBorder(null);
        ButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPerfilActionPerformed(evt);
            }
        });

        ButtonMatricula.setBackground(new java.awt.Color(3, 36, 102));
        ButtonMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconmatricula.png"))); // NOI18N
        ButtonMatricula.setBorder(null);
        ButtonMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMatriculaActionPerformed(evt);
            }
        });

        ButtonSocial.setBackground(new java.awt.Color(3, 36, 102));
        ButtonSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSocial.png"))); // NOI18N
        ButtonSocial.setBorder(null);
        ButtonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSocialActionPerformed(evt);
            }
        });

        ButtonCerrar.setBackground(new java.awt.Color(3, 36, 102));
        ButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconcerrarsesion.png"))); // NOI18N
        ButtonCerrar.setToolTipText("");
        ButtonCerrar.setBorder(null);
        ButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIERRAVPnameAlumno.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(ButtonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ButtonMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(ButtonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(ButtonCerrar)
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 830));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setOpaque(true);

        Perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoPerfil.setBackground(new java.awt.Color(42, 47, 46));
        InfoPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotoperfil.png"))); // NOI18N
        InfoPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, -1, -1));

        Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombresActionPerformed(evt);
            }
        });
        InfoPerfil.add(Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 30));
        InfoPerfil.add(Dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 210, 30));
        InfoPerfil.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 30));
        InfoPerfil.add(Facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 30));
        InfoPerfil.add(Escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, 30));
        InfoPerfil.add(Codigoalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 210, 30));
        InfoPerfil.add(Correoalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 210, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Correo electrónico");
        InfoPerfil.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 120, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombres");
        InfoPerfil.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Apellidos");
        InfoPerfil.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DNI");
        InfoPerfil.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 120, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Código de alumno");
        InfoPerfil.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 120, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Escuela profesional");
        InfoPerfil.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Facultad");
        InfoPerfil.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, -1));

        Perfil.add(InfoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 780));

        CRAalumno.setBackground(new java.awt.Color(42, 47, 46));
        CRAalumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ranking vigente.png"))); // NOI18N
        CRAalumno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 370, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mi C.R.A.png"))); // NOI18N
        CRAalumno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 80));

        Perfil.add(CRAalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 670, 780));

        jTabbedPane1.addTab("", Perfil);

        Matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaTurnoFecha.setAutoCreateRowSorter(true);
        TablaTurnoFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turno", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaTurnoFecha.setShowGrid(false);
        TablaTurnoFecha.setShowHorizontalLines(true);
        Tablaturnoalumno.setViewportView(TablaTurnoFecha);
        if (TablaTurnoFecha.getColumnModel().getColumnCount() > 0) {
            TablaTurnoFecha.getColumnModel().getColumn(0).setResizable(false);
            TablaTurnoFecha.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(Tablaturnoalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 810, 680));

        Matricula.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 870, 740));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Turno de matricula.png"))); // NOI18N
        Matricula.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jTabbedPane1.addTab("", Matricula);

        Social.setFocusable(false);
        Social.setOpaque(false);
        Social.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Social.png"))); // NOI18N
        Social.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texto social.png"))); // NOI18N
        Social.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 960, 40));

        Buscargrupo.setBackground(new java.awt.Color(255, 173, 173));
        Buscargrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscador.png"))); // NOI18N
        Buscargrupo.setBorder(null);
        Buscargrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscargrupoActionPerformed(evt);
            }
        });
        Social.add(Buscargrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 40, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("No deseable :");
        Social.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        Notificacion.setBackground(new java.awt.Color(195, 209, 229));
        Notificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campana.png"))); // NOI18N
        Notificacion.setBorder(null);
        Notificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionActionPerformed(evt);
            }
        });
        Social.add(Notificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 60, 50));

        compañeroencontrado.setBackground(new java.awt.Color(233, 238, 255));
        compañeroencontrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        compañeroencontrado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abrirpaneldemensaje.setBackground(new java.awt.Color(255, 217, 217));
        abrirpaneldemensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        abrirpaneldemensaje.setText("Enviar mensaje");
        abrirpaneldemensaje.setBorder(null);
        abrirpaneldemensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirpaneldemensajeActionPerformed(evt);
            }
        });
        compañeroencontrado.add(abrirpaneldemensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 110, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfilsocial.png"))); // NOI18N
        compañeroencontrado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 90));

        cualidadescompañero.setEditable(false);
        cualidadescompañero.setBackground(new java.awt.Color(233, 238, 255));
        cualidadescompañero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cualidadescompañero.setText("Cualidades");
        cualidadescompañero.setToolTipText("");
        cualidadescompañero.setBorder(null);
        cualidadescompañero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cualidadescompañeroActionPerformed(evt);
            }
        });
        compañeroencontrado.add(cualidadescompañero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        nombredecompañero.setEditable(false);
        nombredecompañero.setBackground(new java.awt.Color(233, 238, 255));
        nombredecompañero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombredecompañero.setText("Nombre y apellido");
        nombredecompañero.setBorder(null);
        nombredecompañero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombredecompañeroActionPerformed(evt);
            }
        });
        compañeroencontrado.add(nombredecompañero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        Social.add(compañeroencontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 490, 130));
        compañeroencontrado.setVisible(false);

        Notificacionpanel.setBackground(new java.awt.Color(233, 238, 255));
        Notificacionpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Notificacionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Mensajes recibidos:");
        Notificacionpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        vermensajede.setBackground(new java.awt.Color(136, 244, 228));
        vermensajede.setText("Ver");
        vermensajede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vermensajedeActionPerformed(evt);
            }
        });
        Notificacionpanel.add(vermensajede, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 80, 30));

        teenviounmensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teenviounmensaje.setText("Nombre y apellido te envio un mensaje");
        jScrollPane2.setViewportView(teenviounmensaje);

        Notificacionpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 30));

        minimizarnotis.setBackground(new java.awt.Color(255, 0, 51));
        minimizarnotis.setText("-");
        minimizarnotis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarnotisActionPerformed(evt);
            }
        });
        Notificacionpanel.add(minimizarnotis, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 50, 20));

        Social.add(Notificacionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 440, 110));

        PanelDeMensaje.setBackground(new java.awt.Color(233, 238, 255));
        PanelDeMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelDeMensaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lineamensaje.png"))); // NOI18N
        PanelDeMensaje.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 10));

        recibidordemensaje.setEditable(false);
        recibidordemensaje.setBackground(new java.awt.Color(233, 238, 255));
        recibidordemensaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        recibidordemensaje.setText("Mensaje de Nombre y apellido");
        recibidordemensaje.setBorder(null);
        recibidordemensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibidordemensajeActionPerformed(evt);
            }
        });
        PanelDeMensaje.add(recibidordemensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        chatdemensajes.setBackground(new java.awt.Color(255, 255, 255));
        chatdemensajes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chatdemensajes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Enviarmensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enviarmensaje.png"))); // NOI18N
        Enviarmensaje.setBorder(null);
        Enviarmensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarmensajeActionPerformed(evt);
            }
        });
        chatdemensajes.add(Enviarmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 40, 30));

        escribirmensaje.setText("   Escribir mensaje");
        escribirmensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chatdemensajes.add(escribirmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 370, 30));

        PanelDeMensaje.add(chatdemensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 390));

        cerrarmensaje.setBackground(new java.awt.Color(239, 3, 67));
        cerrarmensaje.setText("X");
        cerrarmensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarmensajeActionPerformed(evt);
            }
        });
        PanelDeMensaje.add(cerrarmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, 30));

        Social.add(PanelDeMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 430, 490));

        loquenoquieroSOCIAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        loquenoquieroSOCIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loquenoquieroSOCIALActionPerformed(evt);
            }
        });
        Social.add(loquenoquieroSOCIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 190, 40));

        loquequieroSOCIAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        loquequieroSOCIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loquequieroSOCIALActionPerformed(evt);
            }
        });
        Social.add(loquequieroSOCIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Mis mensajes :");
        Social.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Mis mensajes :");
        Social.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Deseable :");
        Social.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTabbedPane1.addTab("", Social);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1050, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPerfilActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Perfil);
    }//GEN-LAST:event_ButtonPerfilActionPerformed

    private void ButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCerrarActionPerformed
        // TODO add your handling code here:
        Login loginFrame = new Login();
    
        // Hacer visible el JFrame Login
        loginFrame.setVisible(true);
    
        // Cerrar el JFrame actual (SistemaAlumno)
        dispose();
    }//GEN-LAST:event_ButtonCerrarActionPerformed

    private void ButtonMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMatriculaActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Matricula);
    }//GEN-LAST:event_ButtonMatriculaActionPerformed

    private void ButtonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSocialActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Social);
        PanelDeMensaje.setVisible(false);
        Notificacionpanel.setVisible(false);
    }//GEN-LAST:event_ButtonSocialActionPerformed

    private void NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresActionPerformed

    private void abrirpaneldemensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirpaneldemensajeActionPerformed
        // TODO add your handling code here:
        PanelDeMensaje.setVisible(true);
    }//GEN-LAST:event_abrirpaneldemensajeActionPerformed

    private void cualidadescompañeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cualidadescompañeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cualidadescompañeroActionPerformed

    private void recibidordemensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibidordemensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recibidordemensajeActionPerformed

    private void EnviarmensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarmensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarmensajeActionPerformed

    private void cerrarmensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarmensajeActionPerformed
        // TODO add your handling code here:
        PanelDeMensaje.setVisible(false);
    }//GEN-LAST:event_cerrarmensajeActionPerformed

    private void vermensajedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vermensajedeActionPerformed
        // TODO add your handling code here:
        PanelDeMensaje.setVisible(true);
        Notificacionpanel.setVisible(false);
    }//GEN-LAST:event_vermensajedeActionPerformed

    private void minimizarnotisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarnotisActionPerformed
        // TODO add your handling code here:
        Notificacionpanel.setVisible(false);
    }//GEN-LAST:event_minimizarnotisActionPerformed

    private void NotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionActionPerformed
        // TODO add your handling code here:
        Notificacionpanel.setVisible(true);
    }//GEN-LAST:event_NotificacionActionPerformed

    private void loquenoquieroSOCIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loquenoquieroSOCIALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loquenoquieroSOCIALActionPerformed

    private void BuscargrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscargrupoActionPerformed
        // TODO add your handling code here:
        compañeroencontrado.setVisible(true);
    }//GEN-LAST:event_BuscargrupoActionPerformed

    private void loquequieroSOCIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loquequieroSOCIALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loquequieroSOCIALActionPerformed

    private void nombredecompañeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombredecompañeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombredecompañeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos;
    private javax.swing.JButton Buscargrupo;
    private javax.swing.JButton ButtonCerrar;
    private javax.swing.JButton ButtonMatricula;
    private javax.swing.JButton ButtonPerfil;
    private javax.swing.JButton ButtonSocial;
    private javax.swing.JPanel CRAalumno;
    private javax.swing.JTextField Codigoalumno;
    private javax.swing.JTextField Correoalumno;
    private javax.swing.JTextField Dni;
    private javax.swing.JButton Enviarmensaje;
    private javax.swing.JTextField Escuela;
    private javax.swing.JTextField Facultad;
    private javax.swing.JPanel InfoPerfil;
    private javax.swing.JPanel Matricula;
    private javax.swing.JTextField Nombres;
    private javax.swing.JButton Notificacion;
    private javax.swing.JPanel Notificacionpanel;
    private javax.swing.JPanel PanelDeMensaje;
    private javax.swing.JPanel Perfil;
    private javax.swing.JPanel Social;
    private javax.swing.JTable TablaTurnoFecha;
    private javax.swing.JScrollPane Tablaturnoalumno;
    private javax.swing.JButton abrirpaneldemensaje;
    private javax.swing.JButton cerrarmensaje;
    private javax.swing.JPanel chatdemensajes;
    private javax.swing.JPanel compañeroencontrado;
    private javax.swing.JTextField cualidadescompañero;
    private javax.swing.JTextField escribirmensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JComboBox<String> loquenoquieroSOCIAL;
    private javax.swing.JComboBox<String> loquequieroSOCIAL;
    private javax.swing.JButton minimizarnotis;
    private javax.swing.JTextField nombredecompañero;
    private javax.swing.JTextField recibidordemensaje;
    private javax.swing.JTextPane teenviounmensaje;
    private javax.swing.JButton vermensajede;
    // End of variables declaration//GEN-END:variables
}
