/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.killa.sierravp.gui;

/**
 *
 * @author jaraj
 */
public class SistemaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form SistemaAlumno
     */
    public SistemaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonPerfil = new javax.swing.JButton();
        ButtonMatricula = new javax.swing.JButton();
        ButtonSocial = new javax.swing.JButton();
        ButtonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Perfil = new javax.swing.JPanel();
        InfoPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        CRAalumno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Matricula = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTurnoFecha = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Social = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        PanelDeMensaje = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 26, 78));

        ButtonPerfil.setBackground(new java.awt.Color(3, 36, 102));
        ButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfilicon.png"))); // NOI18N
        ButtonPerfil.setBorder(null);
        ButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPerfilActionPerformed(evt);
            }
        });

        ButtonMatricula.setBackground(new java.awt.Color(3, 36, 102));
        ButtonMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconmatricula.png"))); // NOI18N
        ButtonMatricula.setBorder(null);
        ButtonMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMatriculaActionPerformed(evt);
            }
        });

        ButtonSocial.setBackground(new java.awt.Color(3, 36, 102));
        ButtonSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSocial.png"))); // NOI18N
        ButtonSocial.setBorder(null);
        ButtonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSocialActionPerformed(evt);
            }
        });

        ButtonCerrar.setBackground(new java.awt.Color(3, 36, 102));
        ButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconcerrarsesion.png"))); // NOI18N
        ButtonCerrar.setToolTipText("");
        ButtonCerrar.setBorder(null);
        ButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIERRAVPnameAlumno.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(ButtonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ButtonMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(ButtonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(ButtonCerrar)
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 830));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setOpaque(true);

        Perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoPerfil.setBackground(new java.awt.Color(42, 47, 46));
        InfoPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotoperfil.png"))); // NOI18N
        InfoPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        InfoPerfil.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 30));
        InfoPerfil.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 210, 30));
        InfoPerfil.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 30));
        InfoPerfil.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 30));
        InfoPerfil.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, 30));
        InfoPerfil.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 210, 30));
        InfoPerfil.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 210, 30));

        Perfil.add(InfoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 780));

        CRAalumno.setBackground(new java.awt.Color(42, 47, 46));
        CRAalumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ranking vigente.png"))); // NOI18N
        CRAalumno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 370, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mi C.R.A.png"))); // NOI18N
        CRAalumno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 80));

        Perfil.add(CRAalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 670, 780));

        jTabbedPane1.addTab("", Perfil);

        Matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaTurnoFecha.setAutoCreateRowSorter(true);
        TablaTurnoFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turno", "Fecha"
            }
        ));
        TablaTurnoFecha.setShowGrid(false);
        TablaTurnoFecha.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(TablaTurnoFecha);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 810, 680));

        Matricula.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 870, 740));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Turno de matricula.png"))); // NOI18N
        Matricula.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jTabbedPane1.addTab("", Matricula);

        Social.setFocusable(false);
        Social.setOpaque(false);
        Social.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Social.png"))); // NOI18N
        Social.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texto social.png"))); // NOI18N
        Social.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 960, 40));

        jTextField8.setText("    Busca un compañero");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Social.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 320, 30));

        jButton1.setBackground(new java.awt.Color(255, 173, 173));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscador.png"))); // NOI18N
        jButton1.setBorder(null);
        Social.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 40, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Mis mensajes :");
        Social.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.setToolTipText("");
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        Social.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 50, 30));

        jButton2.setBackground(new java.awt.Color(161, 255, 128));
        jButton2.setFont(jButton2.getFont().deriveFont((jButton2.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, jButton2.getFont().getSize()+2));
        jButton2.setText("Limitar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Social.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 90, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Limita tu busqueda :");
        Social.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jButton3.setBackground(new java.awt.Color(195, 209, 229));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campana.png"))); // NOI18N
        jButton3.setBorder(null);
        Social.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 60, 50));

        jPanel3.setBackground(new java.awt.Color(233, 238, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 217, 217));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Enviar mensaje");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 110, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfilsocial.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 90));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(233, 238, 255));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setText("Cualidades");
        jTextField9.setToolTipText("");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(233, 238, 255));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField11.setText("Nombre y apellido");
        jTextField11.setBorder(null);
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        Social.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 490, 130));

        PanelDeMensaje.setBackground(new java.awt.Color(233, 238, 255));
        PanelDeMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelDeMensaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lineamensaje.png"))); // NOI18N
        PanelDeMensaje.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 10));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(233, 238, 255));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField10.setText("Mensaje de Nombre y apellido");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        PanelDeMensaje.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enviarmensaje.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 40, 30));

        jTextField12.setText("   Escribir mensaje");
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 370, 30));

        PanelDeMensaje.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 390));

        jButton6.setBackground(new java.awt.Color(190, 0, 51));
        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelDeMensaje.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, 30));

        Social.add(PanelDeMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 430, 490));

        jTabbedPane1.addTab("", Social);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1050, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPerfilActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Perfil);
    }//GEN-LAST:event_ButtonPerfilActionPerformed

    private void ButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCerrarActionPerformed
        // TODO add your handling code here:
        Login loginFrame = new Login();
    
        // Hacer visible el JFrame Login
        loginFrame.setVisible(true);
    
        // Cerrar el JFrame actual (SistemaAlumno)
        dispose();
    }//GEN-LAST:event_ButtonCerrarActionPerformed

    private void ButtonMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMatriculaActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Matricula);
    }//GEN-LAST:event_ButtonMatriculaActionPerformed

    private void ButtonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSocialActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Social);
        PanelDeMensaje.setVisible(false);
    }//GEN-LAST:event_ButtonSocialActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PanelDeMensaje.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        PanelDeMensaje.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCerrar;
    private javax.swing.JButton ButtonMatricula;
    private javax.swing.JButton ButtonPerfil;
    private javax.swing.JButton ButtonSocial;
    private javax.swing.JPanel CRAalumno;
    private javax.swing.JPanel InfoPerfil;
    private javax.swing.JPanel Matricula;
    private javax.swing.JPanel PanelDeMensaje;
    private javax.swing.JPanel Perfil;
    private javax.swing.JPanel Social;
    private javax.swing.JTable TablaTurnoFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
